project:
  type: book
  output-dir: docs

book:
  title: "InCiSE 2019: Technical Report"
  date: "25 April 2019"
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - 00_contents.qmd
    - 00_readers_guide.qmd
    - 01_introduction.qmd
    - 02_index.qmd
    - part: 03_00_indicators.qmd
      chapters:
        - 03_01_integrity.qmd
        - 03_02_openness.qmd
        - 03_03_capabilities.qmd
        - 03_04_inclusiveness.qmd
        - 03_05_policy_making.qmd
        - 03_06_fiscal_financial.qmd
        - 03_07_regulation.qmd
        - 03_08_crisis_risk.qmd
        - 03_09_procurement.qmd
        - 03_10_hrm.qmd
        - 03_11_tax.qmd
        - 03_12_digital.qmd
    - 04_changes.qmd
    - 05_sensitivity.qmd
    - 06_future_development.qmd
    - 99_references.qmd
  appendices: 
    - A_composite_metrics.qmd
    - B_sensitivity_detailed.qmd
    - C_dqa_detailed.qmd
  sidebar:
    collapse-level: 1
  navbar:
    background: dark
    right:
      - text: "More"
        menu:
          - text: "Read the InCiSE 2019 Results Report"
            icon: book-half
            href: https://incise-project.github.io/incise2019-results/
          - text: "Download the PDF of this report"
            icon: file-earmark-pdf
            href: incise2019_technical_report.pdf
          - text: "View the source code of this report"
            icon: github
            href: https://github.com/incise-project/incise2019-techreport/
          - text: "Go to the InCiSE Project homepage"
            icon: house-fill
            href: https://incise-project.github.io/
  cover-image: figures/incise2019-techreport-cover.png
  url: https://incise-project.github.io/incise2019-techreport/
  keyword: international civil service effectiveness, civil service, government,
    effectiveness, performance, public management, public governance

execute:
  freeze: auto

bibliography: references/references.bib
csl: european-journal-of-political-research.csl

format:
  html:
    theme:
      - cosmo
      - custom.scss
    fig-cap-location: top
    fig-format: svg
    fig-responsive: true
    tbl-cap-location: top
    reference-location: margin
    strip-comments: true
    toc-title: "In this chapter"
